###########
# site.title, site.url, site.author.name

title:   'Jekyll Minimal Theme'
author:
  name:  'Jekyll Minimal Theme Team'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  -> Input your Github Repository Name e.g : //myGithubID.github.com

#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#  -> Input your Full Github.io URL e.g : 'http://myGithubID.github.io/'
path: //henrythemes.github.io/jekyll-minimal-theme
url:  'http://henrythemes.github.io/'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

